package zad7;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.ArrayList;

/**
 * @author Paweł Głogowski
 * 
 */
public class NewJPanel extends javax.swing.JPanel {
    private double x,y;
    
    Trojkat trojkat = new Trojkat(new Punkt(0,0), new Punkt(0,50), new Punkt(50,0));
    ArrayList<Trojkat> tablica = new ArrayList<Trojkat>();
    
    
    /** Creates new form NewJPanel */
    public NewJPanel() {
        initComponents();
        tablica.add(new Trojkat(new Punkt(100,100), new Punkt(100,150), new Punkt(150,100)));
    }
  
    @Override
    public void paint(Graphics x)
    {
        Graphics2D g = (Graphics2D)x;
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        super.paint(g);
        
        for (Trojkat trojk: tablica)
        {
            trojk.Rysuj(g);
        }
        
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        x=evt.getX();
        y=evt.getY();

        if (tablica.size() > 0)
        {
            
            tablica.get(tablica.size() - 1).Koloruj(Color.YELLOW);
        }
        
        tablica.add(new Trojkat(new Punkt(x,y), new Punkt(x, y+50 ), new Punkt(x+50, y)));
        
        repaint();
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
